### ISSUE TITLE
version compare issues across multiple ext's

### ISSUE THREAD

**Issue by heatonjb** [mageplus/mageplus#115]
Just encountered some code in the Brim Grouped-Options ext which only applies a specific fix to magento versions > 1.7.0.0.
Mageplus returns the mageplus version number. 

Should Mage::getVersion return the the Mageplus version or the Magento CE version?

``` php
/* BEGIN Brim Grouped-Options Customizations */
        if (version_compare(Mage::getVersion(), '1.7.0.0-rc1') >= 0) {
```

This could cause issues in other Magento ext's also.  Not sure if this method above is common practice or not?

**Comment by leesbian** [comment]
I think it's bad practice in the extension - apart from being incompatible with PE or EE, it's also making the assumption that behaviour in the affected class has not been altered via an override

I'm also not entirely convinced that version_compare (http://uk3.php.net/manual/en/function.version-compare.php) works correctly with the Magento versioning standard

**Comment by heatonjb** [comment]
I agree then it's certainly just bad practice.
