### ISSUE TITLE
add "compatibility mode" switch in admin to report Magento base version instead of MagePlus version

### ISSUE THREAD

**Issue by leesbian** [mageplus/mageplus#119]
a number of poorly written extensions use code like this....

if (preg_match('/^1.4.0/', Mage::getVersion()) || preg_match('/^1.3/', Mage::getVersion())) 

These modules don't work correctly in Mage+ because it''s version numbering started at 1.0

Compatibility mode, when enabled, would report back the version of Magento CE which Mage+ is based on, rather than the current version of Mage+

**Comment by lstrojny** [comment]
+1

**Comment by leesbian** [comment]
This feature is in the branch https://github.com/mageplus/mageplus/tree/feature/COMPATIBILITY-MODE, but isn't merged yet because I haven't yet been able to test

Will hopefully test in the next few days

**Comment by leesbian** [comment]
fixed in commit 1d8136b9ec6e1fd528df72dce3cc6c61c2893189
