### ISSUE TITLE
Customer View's «Shopping Cart»  container is always empty

### ISSUE THREAD

**Issue by rndstr** [mageplus/mageplus#125]
The «Shopping Cart» container is a box you click on and it lists all the items in your shopping cart.  The controller action did not set the website id which leads to the container always being empty (while the heading says N items).

This bug exists in Magento EE 1.12.0.2 while it is absent in EE 1.11.02. Also, in magento2 it seems to be fixed so it will likely be already in the next Magento release.

**Comment by ghost** [comment]
Thanks for the fix, I wonder why magento has too much critical bugs in its platform.
