### ISSUE TITLE
Error Message on DB Configuration Dialog

### ISSUE THREAD

**Issue by densanki** [mageplus/mageplus#139]
Hey MagePlus,

my first installation with mage+ was stopped by this error in DB Configuration Dialog.

PHP Extensions "0" must be loaded.

Only System configuration I found who is maybe wrong was PHP 5.4.6 maybe to new version. Apache2 and MySQL and PHP Setup as Ubuntu64 V12 automatic setup.

Only Fix I found on the www was:
Change Line 64 in /app/code/core/Mage/Install/Model/Installer/Db.php
Add following if($extName ==0) continue; into the foreach statment.

Can you Implement this Fix into the Mage+, for other noobs that install mage+ and get  frustrated night about. Thanks for future implementation.

![densanki de_9999 - Remotedesktopverbindung_2013-03-05_13-38-48](https://f.cloud.github.com/assets/3776155/221353/3a9ac0e6-8597-11e2-8a8f-654013ee6732.png)

![densanki de_9999 - Remotedesktopverbindung_2013-03-05_13-38-07](https://f.cloud.github.com/assets/3776155/221357/466036b8-8597-11e2-8536-2830642d1975.png)

**Comment by hunslater** [comment]
Hi densanki!

Can you attach your local.xml

When I try to put ";" in the  "<initStatements>" tag I had same error message.

use this: 

``` xml
<initStatements><![CDATA[SET NAMES utf8]]></initStatements>
```

Or the other possibility

Replace in file app/code/core/Mage/Install/etc/config.xml (near 71th string) this

``` xml
<extensions>
    <pdo_mysql/>
</extensions>
```

with this

``` xml
<extensions>
    <pdo_mysql>1</pdo_mysql>
</extensions>
```

http://www.randomhacks.co.uk/magento-php-extensions-0-must-be-loaded/

current position in the code:

https://github.com/mageplus/mageplus/blob/master/app/code/core/Mage/Install/etc/config.xml#L71
