### ISSUE TITLE
diff file between magento and mageplus

### ISSUE THREAD

**Issue by gondo** [mageplus/mageplus#144]
would be very useful to include diff file for easy comparison between  mageplus and original magento release. it would give me much more confidence in this project if i could easily see what was modified.

**Comment by LeeSaferite** [comment]
Making a diff file would be a one off thing with no real context and you could only trust it as far as you trusted the mageplus project already.

Better is to make your own diff.  Here is how you do it using my mirror of the Magento source code.  You could do the same with your own mirror as well.

``` bash
git clone --origin mageplus https://github.com/mageplus/mageplus.git
cd mageplus
git remote add magento https://github.com/LokeyCoding/magento-mirror.git
git fetch magento
git diff --name-status -w 1.7.0.2..mageplus/master
git diff -w 1.7.0.2..mageplus/master
```
