### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by amon-ra** [mageplus/mageplus#146]

**Comment by ghost** [comment]
yes it is :)

**Comment by SchumacherFM** [comment]
And nowadays?

**Comment by ghost** [comment]
the latest commit was 5 months ago ...

**Comment by SchumacherFM** [comment]
So not active ;-)

**Comment by leesbian** [comment]
There haven't been any commits - that doesn't mean it's not active - Mage+ is still being actively used in production environments

You're welcome to make a pull request - the focus at the moment is on fixing bugs and improving stability, rather than adding new features
