### ISSUE TITLE
Bug in function isOrderIncrementIdUsed

### ISSUE THREAD

**Issue by leesbian** [mageplus/mageplus#54]
In the function isOrderIncrementIdUsed the orderIncrementId is casted to an integer 
"$bind = array(':increment_id' => (int)$orderIncrementId);" In case of big id's (4000000000+ in our case) and a 32bit system / php version, the orderIncrementId is silently casted to the maximum amount of a 32bit integer which results in a non working check and a duplicate constraint error on the checkout page. this only happens after submitting an order for the second time ( for example: after a payment failure or selecting a previous made order).

Fixed by removing the int cast: $bind = array(':increment_id' => $orderIncrementId);

imported from : http://www.magentocommerce.com/bug-tracking/issue?issue=13596

**Comment by SRaromicon** [comment]
I think the bigger issue is, that alphanumeric IncrementIds and Ids with a custom prefix will be casted to int.
We fix this.
