### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by natebrunette** [mageplus/mageplus#82]
Searching is now using ORs instead of ANDs causing searches to show completely unrelated products.

**Comment by LeeSaferite** [comment]
Is this behavior change in core Magento or specifically in Mage+?

**Comment by LeeSaferite** [comment]
Have you found where the problem is and can you submit a pull request with the fix?

**Comment by ghost** [comment]
It's in core Magento.  What seems to work is changing OR back to AND in 2 places in the prepareResult() method of Mage_CatalogSearch_Model_Resource_Fulltext

**Comment by ghost** [comment]
I can submit a pull

**Comment by natebrunette** [comment]
bd1c095
