### ISSUE TITLE
inabilitie to add breadcrumbs from layout.xml

### ISSUE THREAD

**Issue by Flyingmana** [mageplus/mageplus#84]
we have the block Mage_Page_Block_Html_Breadcrumbs
this block has a addCrumb method, but this method depends on a complex datatype(array) which cant be used in layout.xml

so either we make it possible to use associative arrays in layout.xml or we add a method, which does not need an array as input.

**Comment by Flyingmana** [comment]
a Solution from a recent project:

```
function addLayoutCrumb($crumbName, $label, $title, $link = '')
{
    if($link !== '' || $crumbName == 'home' ){
        return $this->addCrumb($crumbName, array('label'=>$label,'title'=>$title,'link'=>Mage::getBaseUrl().$link));    
    }else{
        return $this->addCrumb($crumbName, array('label'=>$label,'title'=>$title,'link'=>$link));
    }
}
```

its a little specialized and needs to get changed a bit, but serves good for how it could look.

**Comment by LeeSaferite** [comment]
Are you sure this is not possible via layout XML?

```

<reference name="breadcrumbs">
    <action method="addCrumb">
        <crumbName></crumbName>
        <crumbInfo>
            <label></label>
            <title></title>
            <link></link>
            <first></first>
            <last></last>
            <readonly></readonly>
        </crumbInfo>                    
    </action>
</reference>
```

Now, in all fairness, they don't support helper attributes on subkeys so you are SOL there.

**Comment by LeeSaferite** [comment]
Just to be clear.

The layout XML **does** support complex associative arrays of data for values.  You unfortunately do not get the ability to replace a subkey value with the result of a helper call.  That only functions with top level arguments.

Of course, you could have a helper that accepted the complex 'crumbInfo' array as an input and parsed the URL fields to generate URLs on the fly.  That would work.  And would be non-intrusive.

**Comment by LeeSaferite** [comment]
For instance

``` xml
<reference name="breadcrumbs">
    <action method="addCrumb">
        <crumbName></crumbName>
        <crumbInfo helper="My_SuperSpiffyModule/Data/processBreadcrumbInfo">
            <label></label>
            <title></title>
            <link></link>
            <first></first>
            <last></last>
            <readonly></readonly>
        </crumbInfo>                    
    </action>
</reference>
```

Then you define a helper

``` php
<?php
class My_SuperSpiffyModule_Helper_Data extends Mage_Core_Helper_Abstract
{
    public function processBreadcrumbInfo($info)
    {
        // Do something to the array
        return $info;
    }
}
```
